# from Exercise import Exercise
from .Exercise import ML_Exercise
import os

# from FeatureLoader import get_features
# from Normalizer import normaliseValues
root = os.getcwd()

training_data = [
    [ML_Exercise((1,
              "squat",
              None,
              None,
              None,
              f"{root}/ml_analysis/training_data/csvs/bad_squat_1.csv",
               "bad",
               ), "mediapipe"), 0],

    [ML_Exercise((2,
              "squat",
              None,
              None,
              None,
              f"{root}/ml_analysis/training_data/csvs/bad_squat_2.csv",
               "bad",
               ), "mediapipe"), 0],

    [ML_Exercise((3,
              "squat",
              None,
              None,
              None,
              f"{root}/ml_analysis/training_data/csvs/good_squat_1.csv",
               "good",
               ), "mediapipe"), 1],

    [ML_Exercise((4,
              "squat",
              None,
              None,
              None,
              f"{root}/ml_analysis/training_data/csvs/good_squat_2.csv",
               "good",
               ), "mediapipe"), 1],
    [ML_Exercise((5,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_3.csv",
            "good",
            ), "mediapipe"), 1],
    [ML_Exercise((6,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_4.csv",
            "good",
            ), "mediapipe"), 1],
    [ML_Exercise((7,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_3.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((8,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_4.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((9,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_5.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((10,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_6.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((11,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_7.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((12,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_8.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((13,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_9.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((14,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_10.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((15,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/bad_squat_11.csv",
            "bad",
            ), "mediapipe"), 0],
    [ML_Exercise((16,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_5.csv",
            "good",
            ), "mediapipe"), 1],
    [ML_Exercise((17,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_6.csv",
            "good",
            ), "mediapipe"), 1],
    [ML_Exercise((18,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_7.csv",
            "good",
            ), "mediapipe"), 1],
    [ML_Exercise((19,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_8.csv",
            "good",
            ), "mediapipe"), 1],
    [ML_Exercise((20,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_9.csv",
            "good",
            ), "mediapipe"), 1],
            # Removed due to incomplete data
    [ML_Exercise((21,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_10.csv",
            "good",
            ), "mediapipe"), 1],
    [ML_Exercise((22,
            "squat",
            None,
            None,
            None,
            f"{root}/ml_analysis/training_data/csvs/good_squat_11.csv",
            "good",
            ), "mediapipe"), 1],
 
]


