# Generated by Django 4.1.7 on 2023-04-08 14:16

import django.core.validators
from django.db import migrations, models
import gymbuddyapi.models


class Migration(migrations.Migration):

    dependencies = [
        ("gymbuddyapi", "0002_alter_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="csv_file",
            field=models.FileField(
                null=True,
                upload_to=gymbuddyapi.models.get_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="quality",
            field=models.CharField(
                choices=[("unchecked", "Unchecked"), ("good", "Good"), ("bad", "Bad")],
                default="unchecked",
                max_length=10,
            ),
        ),
    ]
